version: '3.8'

services:
  planner_api:
    container_name: planner_api
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    
    volumes:
      - .:/app
    ports:
      - 8000:8000